site_name: Permeation
site_description: Numerical solutions for hydrogen permeation in Python
docs_dir: docs
repo_url: ""

theme:
  name: material
  logo: assets/h2icon.svg
  favicon: assets/h2icon.svg  
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - navigation.tabs
    - content.image.zoom
  palette:
    - scheme: bh-dark
      primary: custom
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: amber
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables
  - md_in_html

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - styles/brand.css

# Top-right repo link
repo_url: https://github.com/queezz/PermeationFit
repo_name: queezz/PermeationFit

# MARK: nav
nav:
  - ğŸ  Home: index.md
  - ğŸ§  Theory:
      - Backward Euler: theory/backward-euler.md
      - ğŸŒŠ Diffusion equation: theory/diffusion.md
      - ğŸ§® Finite difference methods: theory/finite-methods.md
  - ğŸ“š References:
      - ğŸ•°ï¸ History: reference/history.md
      - ğŸ¶ Notation: reference/notation.md
      - ğŸ“ Equation cheat sheet: reference/equations.md
